# Section 7 module 1
# [Lift Off!]
#############################################################################
# Task Description:
# Create a program that counts down when the user enters the second to start
# on. Example shown below
#############################################################################
# Your Output should be like this:
# Time to launch: 10
# Counting down ...
# 10 ...
# 9 ...
# 8 ...
# 7 ...
# 6 ...
# 5 ...
# 4 ...
# 3 ...
# 2 ...
# 1 ...
# Lift Off!
#############################################################################
